force-app/main/default/objects/Reservation__c/Reservation__c.object-meta.xml
<CustomObject>
    <label>Reservation</label>
    <nameField>
        <displayFormat>RE-{0000}</displayFormat>
        <label>Reservation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reservations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Reservation__c/fields/Booking_Date__c.field-meta.xml
<CustomField>
    <fullName>Booking_Date__c</fullName>
    <formula>TODAY()</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Booking Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Reservation__c/fields/Table_No__c.field-meta.xml
<CustomField>
    <fullName>Table_No__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Table No</label>
    <referenceTo>Table__c</referenceTo>
    <relationshipLabel>Reservations</relationshipLabel>
    <relationshipName>Reservations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Table__c/Table__c.object-meta.xml
<CustomObject>
    <label>Table</label>
    <nameField>
        <label>Table Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Table</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/BookingConfirmationEmailTriggerHandler.cls
public class BookingConfirmationEmailTriggerHandler {
    public static void sendEmailNotification(List<Reservation__c> rsvList) {
        List<Messaging.SingleEmailMessage> emailList = new List<Messaging.SingleEmailMessage>();

        for (Reservation__c rsv : rsvList) {
            if (rsv.Email__c != null) {
                Messaging.SingleEmailMessage emailMsg = new Messaging.SingleEmailMessage();
                String[] toAddress = new String[]{rsv.Email__c};
                emailMsg.setToAddresses(toAddress);
                emailMsg.setSenderDisplayName('Happy Singh');
                //emailMsg.

                Id userId = rsv.User__c;
                
                // Query the User object to retrieve User Names based on User Ids
                User recipientUser = [SELECT Id, Name, Email FROM User WHERE Id = :userId LIMIT 1];

                String emailSub = 'Welcome ' + recipientUser.Name;
                emailMsg.setSubject(emailSub);
                
                String recordId = rsv.Table_No__c;
                Table__c retrievedRecord = [SELECT Name FROM Table__c WHERE Id = :recordId LIMIT 1];

                String content = 'Hi ' + recipientUser.Name + ',' + '<br/><br/>' +
                    'Your Table no ' + retrievedRecord.Name + ' for date ' + rsv.Booking_Date__c + ' has been booked';
                emailMsg.setHtmlBody(content);
                emailList.add(emailMsg);
            }
        }

        if (!emailList.isEmpty()) {
            try {
                Messaging.sendEmail(emailList);
            } catch (Exception e) {
                System.debug('Email sending failed: ' + e.getMessage());
                // Handle email sending errors here, if needed
            }
        }
    }
}