force-app/main/default/objects/Reservation__c/Reservation__c.object-meta.xml
<CustomObject>
    <label>Reservation</label>
    <nameField>
        <displayFormat>RE-{0000}</displayFormat>
        <label>Reservation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reservations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Reservation__c/fields/Table_No__c.field-meta.xml
<CustomField>
    <fullName>Table_No__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Table No</label>
    <referenceTo>Table__c</referenceTo>
    <relationshipLabel>Reservations</relationshipLabel>
    <relationshipName>Reservations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Table__c/Table__c.object-meta.xml
<CustomObject>
    <label>Table</label>
    <nameField>
        <label>Table Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Table</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Table__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/UpdateTableStatusHandler.cls
public class UpdateTableStatusHandler {
    public static void updateTableStatus(List<Reservation__c> newReservations) {
        List<Id> tableIdsToUpdate = new List<Id>();

        for (Reservation__c res : newReservations) {
            tableIdsToUpdate.add(res.Table_No__c);
        }

        List<Table__c> tablesToUpdate = [SELECT Id FROM Table__c WHERE Id IN :tableIdsToUpdate AND Status__c = 'Available'];

        if (!tablesToUpdate.isEmpty()) {
            for (Table__c table : tablesToUpdate) {
                table.Status__c = 'Booked';
            }

            update tablesToUpdate;
        }
    }
}